### ISSUE TITLE
Are you serius?

### ISSUE THREAD

**Issue by Noth-Shian** [KaioHSG/equalizer-apo-bass-booster#2]
You did a repository just for a .txt file with a basic eq?
Damnn, i mean... idk, thank you lol

What about doing a stereo expander or somenthing like that 
Maybe a customizable phase correction config for IEMs, using the EQ APO expressions
A loudness limiter + volume boost with a random free VST2 compressor plugin

Something that only a few people know to do... and share it man
That would be more useful that a basic bass boost eq

**Comment by KaioHSG** [comment]
This is here because I needed a place for it to stay in case I formatted my PC, and since I like to post all my codes here I thought, why not?
After a while I created a little tutorial and I think that's it.
I come back every now and then to update, but nothing much.
I don't know why so many people downloaded it. 🤷
And as for doing something real, I don't need to and I don't want to.
